server:
  port: 8888
  context-path: /v0

spring:
  profiles: default, local
  application:
    name: inv-module
  datasource:
    url: jdbc:mysql://localhost:3306/bti-user-module
    username: root
    password: root
    max-active: 100
    maximum-pool-size: 100
    max-age: 10000
    connection-timeout: 30000
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    #hibernate:
     # ddl-auto: update

dbpath:
  dbcreation: 'jdbc:mysql://localhost/?user=root&password=root'
  dbscriptcreate1: jdbc:mysql://localhost/
  dbscriptcreate2: '?user=root&password=root'
  
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
ribbon:
  eureka:
    enabled: true     