server:
  port: 8888
spring:
  h2:
    console:
      enabled: true     
      path: /h2
  application:
    name: inv-module
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: null
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
ribbon:
  eureka:
    enabled: false     