>cd usr/local/mysql/bin/
>./mysql -u root -p 
password: temp password
mysql> ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';
mysql> source /.../abc.script

DROP TABLE IF EXISTS `bti-user-module`.`IV40200`;
create table IF NOT EXISTS `bti-user-module`.`IV40200` 
(
 LOCNCODIND INTEGER AUTO_INCREMENT,
 LOCNCODCODE VARCHAR(7) NOT NULL UNIQUE KEY,
 LOCDSCR VARCHAR(31) ,
 LOCDSCRA VARCHAR(61),
 LOCADRESS VARCHAR(120),
 LOCADRESSA VARCHAR(120),
 LOCCITY VARCHAR(21),
 LOCCONTRY VARCHAR(31),
 LOCPHONE VARCHAR(21),
 LOCFAX VARCHAR(21),
 DIMINXVALUE INT ,
 TAXSCHDIDS VARCHAR(15),
 TAXSCHDIDP VARCHAR(15),
 CREATDDT DATE,
 MODIFDT DATE,
 CHANGEBY VARCHAR(15),
 DEX_ROW_TS TIMESTAMP,
 DEX_ROW_ID INT,
 PRIMARY KEY PK_IV40200_LOCNCODEIND_LOCNCODCODE (LOCNCODIND,LOCNCODCODE)
);

DROP TABLE IF EXISTS `bti-user-module`.`IV40201`;
CREATE TABLE IF NOT EXISTS `bti-user-module`.`IV40201`
(
LOCNCODIND INTEGER REFERENCES IV40200(LOCNCODIND),
LOCNCODE VARCHAR(7)  REFERENCES IV40200(LOCNCODCODE),
LOCBIN VARCHAR(21),
LOCPHONE VARCHAR(21),
LOCFAX VARCHAR(21),
LOCNBINSEQ INTEGER PRIMARY KEY AUTO_INCREMENT,
CREATDDT TIMESTAMP,
MODIFDT TIMESTAMP,
CHANGEBY VARCHAR(15) ,
DEX_ROW_TS TIMESTAMP,
DEX_ROW_ID INTEGER,
PRIMARY KEY PK_IV40201(LOCNCODIND,LOCNCODE)
);

PRIMARY KEY AUTO_INCREMENT
UPDATE `bti-user-module`.`USER` set password='$2a$10$nuiG62PnhmnWGrQP0iMK1ucUFLHgCCDoHlhjUDcJrdhlwzy2KJ7BS'
where user_id=161;

UPDATE `bti-user-module`.`USER` set role_id=2 where user_id=161;